version: 2

jobs:
  build:
    docker:
      - image: golang:1.6.4
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - restore_cache:
          key: dependency-cache
      - run:
          name: docker build test
          command: |
            docker build -t uzyexe/terraform .
      - run:
          name: Make ~/docker directory
          command: |
            mkdir -p ~/docker
      - run:
          name: Save New uzyexe/terraform docker image
          command: |
            docker save uzyexe/terraform > ~/docker/image.tar
      - save_cache:
          key: dependency-cache
          paths:
            - "~/docker"
      - run:
          name: Show Terraform version
          command: |
            docker run uzyexe/terraform version
      - deploy:
          name: Deploy Master to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push uzyexe/terraform
            fi
